type Race={id:number;race_number:number;race_date:string;scheduled_time:string|null;distance_meters:number;surface:string;track:{name:string;city:string}};
type Entry={id?:number;entry_id?:number;program_number:number;horse_id?:number;horse_name:string|null;handicap_rating:number|null;agf_percent:number|null;weight_kg:number|null;win_probability?:number;jockey_name?:string|null;trainer_name?:string|null};
type Daily={race_id:number;chaos_index:number;top_entry:Entry};
type Candidate={program_number:number;horse_id?:number;horse_name:string|null;win_probability:number;model_score?:number|null;agf_percent?:number|null;value_gap?:number|null;strengths:{label:string;detail:string}[];risks:{label:string;detail:string}[]};
type Explanation={model_version?:string;candidates:Candidate[]};
const api='http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Programa d\u00f6n',detail:'KO\u015eU DETAYI',race:'Ko\u015fu',probability:'Kazanma olas\u0131l\u0131\u011f\u0131',model:'MODEL \u00d6NER\u0130S\u0130',chaos:'YARI\u015e R\u0130SK\u0130',value:'DE\u011eER S\u0130NYAL\u0130',entries:'KATILIMCILAR',noData:'Bu ko\u015fu i\u00e7in aktar\u0131lm\u0131\u015f veri bulunamad\u0131.',why:'Neden \u00f6ne \u00e7\u0131k\u0131yor?',risks:'Dikkat edilmesi gerekenler',agf:'AGF',hp:'Handikap',weight:'Kilo',jockey:'Jokey',trainer:'Antren\u00f6r',alternatives:'Alternatifler',guide:'Olas\u0131l\u0131k temelli karar deste\u011fidir; kesin sonu\u00e7 iddias\u0131 ta\u015f\u0131maz.',high:'Y\u00fcksek',medium:'Orta',low:'D\u00fc\u015f\u00fck',waiting:'Veri bekleniyor',dot:'\u00b7'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const response=await fetch(`${api}${path}`,{cache:'no-store'});return response.ok?await response.json() as T:fallback}catch{return fallback}}
function clean(value:string|null|undefined){let text=(value??'').replace(/\\u([0-9a-f]{4})/gi,(_,code)=>String.fromCharCode(parseInt(code,16)));for(let i=0;i<4;i+=1){if(!/[\u00c3\u00c2\u00e2]/.test(text))break;try{text=decodeURIComponent(escape(text))}catch{break}}return text}
function city(value:string){const name=clean(value);return name==='Istanbul'?'\u0130stanbul':name==='Izmir'?'\u0130zmir':name}
function num(value:unknown){const parsed=typeof value==='number'?value:Number(String(value??'').replace(',','.'));return Number.isFinite(parsed)?parsed:null}
function one(value:unknown){const parsed=num(value);return parsed==null?'--':parsed.toFixed(1)}
function risk(chaos:unknown){const value=num(chaos)??0;return value>=70?t.high:value>=40?t.medium:t.low}
export const dynamic='force-dynamic';
export default async function RaceDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const raceId=Number(id);
 const [directRace,entries]=await Promise.all([getJson<Race|null>(`/races/${raceId}`,null),getJson<Entry[]>(`/races/${raceId}/entries`,[])]);
 const race=directRace??(await getJson<Race[]>('/races/',[])).find(item=>item.id===raceId)??null;
 if(!race)return <main className="detail-shell"><a href="/">{t.back}</a><div className="detail-empty">{t.noData}</div></main>;
 const daily=await getJson<Daily[]>(`/races/daily-intelligence?race_date=${race.race_date}`,[]);
 const intelligence=daily.find(item=>item.race_id===raceId);
 const explanation=await getJson<Explanation> (`/explanations/races/${raceId}`,{candidates:[]});
 const ranked=[...explanation.candidates].sort((a,b)=>b.win_probability-a.win_probability);
 const lead=ranked[0];const alternatives=ranked.slice(1,4);
 const entryMap=new Map(entries.map(entry=>[entry.program_number,entry]));
 return <main className="detail-shell">
  <header className="detail-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header>
  <section className="detail-title"><p className="eyebrow">{t.detail}</p><h1>{city(race.track.city)} {race.race_number}. {t.race}</h1><p>{race.scheduled_time?.slice(0,5)??'--:--'} {t.dot} {race.distance_meters}m {t.dot} {clean(race.surface)} {t.dot} {entries.length} at</p></section>
  <section className="detail-hero-grid"><article className="detail-lead"><p className="eyebrow">{t.model}</p>{lead?<><h2>{lead.program_number}. {clean(lead.horse_name)}</h2><div className="probability">%{one(lead.win_probability)}</div><span>{t.probability}</span><p className="detail-copy">{lead.strengths.slice(0,2).map(item=>clean(item.label)).join(' '+t.dot+' ')||t.guide}</p></>:<p>{t.noData}</p>}</article><article className="detail-risk"><p className="eyebrow">{t.chaos}</p><h2>{intelligence?`${one(intelligence.chaos_index)}/100`:'--'}</h2><strong>{intelligence?risk(intelligence.chaos_index):t.waiting}</strong><p>{(num(intelligence?.chaos_index)??0)>=70?'Adaylar birbirine yak\u0131n; kapsaml\u0131 de\u011ferlendirme uygun.':'Model ile piyasa sinyallerini birlikte incele.'}</p></article><article className="detail-value"><p className="eyebrow">{t.value}</p><h2>{lead?.value_gap!=null?`%${one(lead.value_gap)}`:'--'}</h2><p>{lead?.agf_percent!=null?`${t.probability}: %${one(lead.win_probability)} ${t.dot} ${t.agf}: %${one(lead.agf_percent)}`:t.guide}</p></article></section>
  <section className="detail-grid"><article className="detail-panel"><div className="detail-panel-title"><div><p className="eyebrow">{t.why}</p><h2>{lead?`${lead.program_number}. ${clean(lead.horse_name)}`:t.noData}</h2></div><span>{explanation.model_version??'--'}</span></div>{lead?<div className="reason-list">{lead.strengths.map((item,index)=><div key={`${item.label}-${index}`}><b>{clean(item.label)}</b><span>{clean(item.detail)}</span></div>)}</div>:null}{lead?.risks.length?<><p className="eyebrow reason-heading">{t.risks}</p><div className="reason-list risk-list">{lead.risks.map((item,index)=><div key={`${item.label}-${index}`}><b>{clean(item.label)}</b><span>{clean(item.detail)}</span></div>)}</div></>:null}</article><article className="detail-panel"><p className="eyebrow">{t.alternatives}</p><div className="alternative-list">{alternatives.map(candidate=><div key={candidate.program_number}><b>{candidate.program_number}. {clean(candidate.horse_name)}</b><strong>%{one(candidate.win_probability)}</strong><span>{candidate.value_gap!=null?`${t.value} %${one(candidate.value_gap)}`:t.probability}</span></div>)}</div></article></section>
  <section className="detail-panel entrants"><div className="detail-panel-title"><div><p className="eyebrow">{t.entries}</p><h2>{entries.length} at</h2></div><span>{t.guide}</span></div><div className="entrant-table"><div className="entrant-head"><span>No</span><span>At</span><span>{t.hp}</span><span>{t.agf}</span><span>{t.weight}</span><span>{t.jockey}</span></div>{entries.sort((a,b)=>(num(a.program_number)??0)-(num(b.program_number)??0)).map(entry=>{const candidate=ranked.find(item=>item.program_number===entry.program_number);const row=entryMap.get(entry.program_number)??entry;return <div className="entrant-row" key={entry.id??entry.entry_id??entry.program_number}><b>{entry.program_number}</b><div><strong>{entry.horse_id?<a className="horse-link" href={`/horses/${entry.horse_id}`}>{clean(entry.horse_name)}</a>:clean(entry.horse_name)}</strong><small>{candidate?`%${one(candidate.win_probability)} ${t.probability}`:'--'}</small></div><span>{entry.handicap_rating??'--'}</span><span>%{one(entry.agf_percent)}</span><span>{entry.weight_kg??'--'}</span><span>{clean(row.jockey_name)||'--'}</span></div>})}</div></section>
 </main>
}