type Race={id:number;race_number:number;race_date:string;scheduled_time:string|null;distance_meters:number;surface:string;track:{name:string;city:string}};
type Entry={id?:number;entry_id?:number;program_number:number;horse_name:string|null};
type Daily={race_id:number;chaos_index:number|string|null;top_entry:{program_number:number;horse_name:string|null}};
type Safety={can_publish_actionable_scenarios?:boolean;state?:string;verified_race_dates?:number;minimum_race_dates?:number};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Ana ekrana d\u00f6n',tag:'RESM\u0130 G\u00dcNL\u00dcK PROGRAM',title:'G\u00fcn\u00fcn program\u0131, hipodrom baz\u0131nda.',lead:'Ko\u015fular\u0131 saat, pist, mesafe ve resm\u00ee ko\u015fu kart\u0131yla birlikte incele.',empty:'Bug\u00fcn i\u00e7in aktar\u0131lm\u0131\u015f ko\u015fu bulunamad\u0131.',race:'ko\u015fu',horse:'at',review:'Model inceleme modunda',open:'Kart\u0131 a\u00e7 \u2192',dot:'\u00b7',source:'Resm\u00ee program aktar\u0131m\u0131'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const response=await fetch(`${api}${path}`,{cache:'no-store'});return response.ok?await response.json() as T:fallback}catch{return fallback}}
function list<T>(value:unknown):T[]{if(Array.isArray(value))return value as T[];const item=value as {items?:T[];races?:T[]};return item.items||item.races||[]}
function text(value:unknown){return value===null||value===undefined||value===''?'--':String(value)}
function clean(value:string|null|undefined){return (value??'').replace(/\\u([0-9a-f]{4})/gi,(_,code)=>String.fromCharCode(parseInt(code,16)))}
function city(value:string){const name=clean(value);return name==='Istanbul'?'\u0130stanbul':name==='Izmir'?'\u0130zmir':name==='Elazig'?'Elaz\u0131\u011f':name==='Diyarbakir'?'Diyarbak\u0131r':name}
export const dynamic='force-dynamic';
export default async function ProgramPage(){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const [board,rawSafety]=await Promise.all([getJson<{races?:Race[]}>(`/analytics/current-day-board?race_date=${today}`,{races:[]}),getJson<Safety>('/analytics/model-safety',{can_publish_actionable_scenarios:false,state:'review'})]);
 const races=list<Race>(board.races).sort((a,b)=>`${a.track.city}-${a.scheduled_time??''}-${a.race_number}`.localeCompare(`${b.track.city}-${b.scheduled_time??''}-${b.race_number}`,'tr'));
 const entries=await Promise.all(races.map(async race=>[race.id,list<Entry>(await getJson<unknown>(`/races/${race.id}/entries`,[]))] as const));
 const entryByRace=new Map(entries);
 const rawDaily=await getJson<unknown>(`/races/daily-intelligence?race_date=${today}`,[]);
 const daily=list<Daily>(rawDaily); const dailyByRace=new Map(daily.map(item=>[item.race_id,item]));
 const groups=new Map<string,Race[]>();races.forEach(race=>groups.set(race.track.city,[...(groups.get(race.track.city)??[]),race]));
 const safety=rawSafety.can_publish_actionable_scenarios===true;
 return <main className="decision-shell"><header className="decision-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="decision-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{today} {t.dot} {t.lead}</p></section>{!safety?<section className="detail-gate"><b>{t.review}</b><p>Do\u011frulanm\u0131\u015f sonu\u00e7 ve kalibrasyon e\u015fi\u011fi tamamlanmadan aday olas\u0131l\u0131klar\u0131 yay\u0131nlanmaz.</p><small>{rawSafety.verified_race_dates??0}/{rawSafety.minimum_race_dates??20} do\u011frulanm\u0131\u015f g\u00fcn</small></section>:null}{races.length?<section className="decision-list">{[...groups.entries()].map(([track,items])=><section className="performance-panel" key={track}><div><p className="eyebrow">{city(track)}</p><h2>{items.length} {t.race}</h2></div><div className="performance-list">{items.map(race=>{const raceEntries=entryByRace.get(race.id)??[];const intelligence=dailyByRace.get(race.id);return <div key={race.id}><b>{race.scheduled_time?.slice(0,5)??'--:--'} {t.dot} {race.race_number}. {t.race}</b><span>{race.distance_meters}m {t.dot} {clean(race.surface)} {t.dot} {raceEntries.length} {t.horse}</span><span>{safety&&intelligence?`${intelligence.top_entry.program_number}. ${clean(intelligence.top_entry.horse_name)}`:t.source}</span><em>{safety&&intelligence?`Chaos ${text(intelligence.chaos_index)}`:<a href={`/races/${race.id}`}>{t.open}</a>}</em></div>})}</div></section>)}</section>:<div className="decision-empty">{t.empty}</div>}</main>
}