type Race={id:number;race_number:number;race_date:string;scheduled_time:string|null;distance_meters:number;surface:string;race_class:string|null;track:{name:string;city:string}};
type Entry={id?:number;entry_id?:number;program_number:number;horse_name:string|null;win_probability?:number|string|null;agf_percent?:number|string|null;weight_kg?:number|string|null};
type Daily={race_id:number;chaos_index:number|string|null;top_entry:Entry};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Ana ekrana d\u00f6n',tag:'RESM\u0130 G\u00dcNL\u00dcK PROGRAM',title:'G\u00fcn\u00fcn program\u0131, hipodrom baz\u0131nda.',lead:'Ko\u015fular\u0131; saat, pist, mesafe, model birinci aday\u0131 ve belirsizlik sinyaliyle birlikte incele.',empty:'Bu tarih i\u00e7in aktar\u0131lm\u0131\u015f ko\u015fu bulunamad\u0131.',race:'ko\u015fu',horse:'at',model:'Model birinci aday\u0131',open:'Kart\u0131 a\u00e7 \u2192',dot:'\u00b7'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function num(v:unknown){const n=typeof v==='number'?v:Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null}
function clean(value:string|null|undefined){let s=(value??'').replace(/\\u([0-9a-f]{4})/gi,(_,c)=>String.fromCharCode(parseInt(c,16)));for(let i=0;i<4;i+=1){if(!/[\u00c3\u00c2\u00e2]/.test(s))break;try{s=decodeURIComponent(escape(s))}catch{break}}return s}
function city(value:string){const labels:Record<string,string>={Istanbul:'\u0130stanbul',Izmir:'\u0130zmir',Elazig:'Elaz\u0131\u011f',Diyarbakir:'Diyarbak\u0131r'};return labels[value]??value}
export const dynamic='force-dynamic';
export default async function ProgramPage(){const races=await getJson<Race[]>('/races/',[]);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());const dates=[...new Set(races.map(item=>item.race_date))].sort();const activeDate=dates.includes(today)?today:(dates.at(-1)??'');const selected=races.filter(item=>item.race_date===activeDate).sort((a,b)=>`${a.track.name}-${a.race_number}`.localeCompare(`${b.track.name}-${b.race_number}`));const entries=await Promise.all(selected.map(async race=>[race.id,await getJson<Entry[]>(`/races/${race.id}/entries`,[])] as const));const entryByRace=new Map(entries);const daily=activeDate?await getJson<Daily[]>(`/races/daily-intelligence?race_date=${activeDate}`,[]):[];const dailyByRace=new Map(daily.map(item=>[item.race_id,item]));const groups=new Map<string,Race[]>();selected.forEach(race=>groups.set(race.track.name,[...(groups.get(race.track.name)??[]),race]));return <main className="decision-shell"><header className="decision-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="decision-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{activeDate} {t.dot} {t.lead}</p></section>{selected.length?<section className="decision-list">{[...groups.entries()].map(([track,items])=><section className="performance-panel" key={track}><div><p className="eyebrow">{city(track)}</p><h2>{items.length} {t.race}</h2></div><div className="performance-list">{items.map(race=>{const model=dailyByRace.get(race.id);const raceEntries=entryByRace.get(race.id)??[];const lead=model?.top_entry;return <div key={race.id}><b>{race.scheduled_time?.slice(0,5)??'--:--'} {t.dot} {race.race_number}. {t.race}</b><span>{race.distance_meters}m {t.dot} {clean(race.surface)} {t.dot} {raceEntries.length} {t.horse}</span><span>{lead?`${t.model}: ${lead.program_number}. ${clean(lead.horse_name)}`:'--'}</span><em>{model?`Chaos ${num(model.chaos_index)?.toFixed(1)??'--'}`:<a href={`/races/${race.id}`}>{t.open}</a>}</em></div>})}</div></section>)}</section>:<div className="decision-empty">{t.empty}</div>}</main>}