type Detail={race_id:number;city?:string;race_number?:number;winner_program_number:number;predicted_top3:number[];top1_hit:boolean;top3_hit:boolean};
type Performance={evaluated_races:number;top1_hits:number;top3_hits:number;top1_accuracy:number|null;top3_coverage:number|null;details:Detail[]};
type Daily={race_date:string|null;evaluated_races:number;top1_hits:number;top3_hits:number;details:Detail[]};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Programa d\u00f6n',tag:'PERFORMANS TAK\u0130B\u0130',title:'Modelin ge\u00e7mi\u015f performans\u0131.',lead:'Bu sayfa yaln\u0131zca sonucu kay\u0131t alt\u0131na al\u0131nm\u0131\u015f ko\u015fularda, tahmin an\u0131ndaki ilk adaylar\u0131 resmi sonu\u00e7larla kar\u015f\u0131la\u015ft\u0131r\u0131r.',evaluated:'De\u011ferlendirilen ko\u015fu',top1:'Birinci aday isabeti',top3:'\u0130lk \u00fc\u00e7 kapsama',hits:'isabet',recent:'SON DE\u011eERLEND\u0130RMELER',daily:'G\u00dcNL\u00dcK DE\u011eERLEND\u0130RME',winner:'Kazanan',predicted:'Model ilk \u00fc\u00e7',correct:'Birinci aday do\u011fru',covered:'Kazanan ilk \u00fc\u00e7te',miss:'Kapsam d\u0131\u015f\u0131',empty:'Hen\u00fcz sonu\u00e7lanm\u0131\u015f ve tahmin kayd\u0131 e\u015fle\u015fmi\u015f ko\u015fu bulunamad\u0131.',note:'Performans, zaman i\u00e7inde veri ve model s\u00fcr\u00fcm\u00fcyle birlikte de\u011fi\u015fir; garanti anlam\u0131na gelmez.'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function pct(value:number|null|undefined){return value==null?'--':`%${Number(value).toFixed(1)}`}
function city(value:string|undefined){const labels:Record<string,string>={Istanbul:'\u0130stanbul',Izmir:'\u0130zmir',Elazig:'Elaz\u0131\u011f',Diyarbakir:'Diyarbak\u0131r'};return labels[value??'']??value??'--'}
function ResultRows({details}:{details:Detail[]}){return details.length?<div className="performance-list">{details.slice(-16).reverse().map(detail=><div key={detail.race_id}><b>{detail.city?`${city(detail.city)} ${detail.race_number}.`:`#${detail.race_id}`}</b><span>{t.winner}: {detail.winner_program_number}</span><span>{t.predicted}: {detail.predicted_top3.join(' - ')}</span><em className={detail.top1_hit?'hit':detail.top3_hit?'cover':'miss'}>{detail.top1_hit?t.correct:detail.top3_hit?t.covered:t.miss}</em></div>)}</div>:<div className="performance-empty">{t.empty}</div>}
export const dynamic='force-dynamic';
export default async function PerformancePage(){const [p,daily]=await Promise.all([getJson<Performance>('/results/performance',{evaluated_races:0,top1_hits:0,top3_hits:0,top1_accuracy:null,top3_coverage:null,details:[]}),getJson<Daily>('/results/daily-performance',{race_date:null,evaluated_races:0,top1_hits:0,top3_hits:0,details:[]})]);return <main className="performance-shell"><header className="performance-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="performance-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="performance-metrics"><article><span>{t.evaluated}</span><strong>{p.evaluated_races}</strong><small>{t.hits}</small></article><article><span>{t.top1}</span><strong>{pct(p.top1_accuracy)}</strong><small>{p.top1_hits} {t.hits}</small></article><article><span>{t.top3}</span><strong>{pct(p.top3_coverage)}</strong><small>{p.top3_hits} {t.hits}</small></article></section><section className="performance-panel"><div><p className="eyebrow">{t.daily}</p><h2>{daily.race_date??'--'}</h2><small>{daily.evaluated_races} {t.evaluated} \u00b7 {daily.top1_hits} {t.top1}</small></div><ResultRows details={daily.details}/></section><section className="performance-panel"><div><p className="eyebrow">{t.recent}</p><small>{t.note}</small></div><ResultRows details={p.details}/></section></main>}