type Detail={race_id:number;city?:string;race_number?:number;winner_program_number:number;predicted_top3:number[];top1_hit:boolean;top3_hit:boolean;model_version?:string;prediction_generated_at?:string;result_recorded_at?:string};
type Performance={evaluated_races:number;eligible_results:number;excluded_results:number;top1_hits:number;top3_hits:number;top1_accuracy:number|null;top3_coverage:number|null;details:Detail[];evaluation_policy?:string};
type Daily={race_date:string|null;evaluated_races:number;eligible_results:number;excluded_results:number;top1_hits:number;top3_hits:number;top1_accuracy:number|null;top3_coverage:number|null;details:Detail[];evaluation_policy?:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'← Programa dön',tag:'PERFORMANS TAKİBİ',title:'Modelin zaman doğrulamalı geçmiş performansı.',lead:'Sadece resmî sonuç kaydedilmeden önce üretilmiş tahminler değerlendirilir. Sonuçtan sonra yenilenen bir tahmin, geçmiş performans metriklerine dahil edilmez.',evaluated:'Değerlendirilen koşu',excluded:'Hariç tutulan',top1:'Birinci aday isabeti',top3:'İlk üç kapsama',hits:'isabet',recent:'SON DEĞERLENDİRMELER',daily:'GÜNLÜK DEĞERLENDİRME',winner:'Kazanan',predicted:'Model ilk üç',correct:'Birinci aday doğru',covered:'Kazanan ilk üçte',miss:'Kapsam dışı',empty:'Henüz zaman kurallarını karşılayan tahmin-sonuç eşleşmesi bulunamadı.',note:'Bu sayfa geçmiş tahminlerin zaman sırasına uyumunu gösterir; gelecekteki sonuç veya getiri için garanti vermez.'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function pct(value:number|null|undefined){return value==null?'--':`%${Number(value).toFixed(1)}`}
function city(value:string|undefined){const labels:Record<string,string>={Istanbul:'İstanbul',Izmir:'İzmir',Elazig:'Elazığ',Diyarbakir:'Diyarbakır'};return labels[value??'']??value??'--'}
function ResultRows({details}:{details:Detail[]}){return details.length?<div className="performance-list">{details.slice(-16).reverse().map(detail=><div key={detail.race_id}><b>{detail.city?`${city(detail.city)} ${detail.race_number}.`:`#${detail.race_id}`}</b><span>{t.winner}: {detail.winner_program_number}</span><span>{t.predicted}: {detail.predicted_top3.join(' - ')}</span><em className={detail.top1_hit?'hit':detail.top3_hit?'cover':'miss'}>{detail.top1_hit?t.correct:detail.top3_hit?t.covered:t.miss}</em></div>)}</div>:<div className="performance-empty">{t.empty}</div>}
export const dynamic='force-dynamic';
export default async function PerformancePage(){const fallback:Performance={evaluated_races:0,eligible_results:0,excluded_results:0,top1_hits:0,top3_hits:0,top1_accuracy:null,top3_coverage:null,details:[]};const [p,daily]=await Promise.all([getJson<Performance>('/results/performance',fallback),getJson<Daily>('/results/daily-performance',{...fallback,race_date:null})]);return <main className="performance-shell"><header className="performance-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="performance-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="performance-metrics"><article><span>{t.evaluated}</span><strong>{p.evaluated_races}</strong><small>{p.top1_hits} {t.hits}</small></article><article><span>{t.top1}</span><strong>{pct(p.top1_accuracy)}</strong><small>{p.top1_hits} {t.hits}</small></article><article><span>{t.top3}</span><strong>{pct(p.top3_coverage)}</strong><small>{p.top3_hits} {t.hits}</small></article><article><span>{t.excluded}</span><strong>{p.excluded_results}</strong><small>zaman kuralı</small></article></section><section className="performance-panel"><div><p className="eyebrow">{t.daily}</p><h2>{daily.race_date??'--'}</h2><small>{daily.evaluated_races} {t.evaluated} · {daily.excluded_results} {t.excluded}</small></div><ResultRows details={daily.details}/></section><section className="performance-panel"><div><p className="eyebrow">{t.recent}</p><small>{p.evaluation_policy??t.note}</small></div><ResultRows details={p.details}/></section><p className="disclaimer">{t.note}</p></main>}