type Race = { id:number; race_number:number; race_date:string; scheduled_time:string|null; distance_meters:number; surface:string; track:{name:string;city:string} };
type Entry = { id?:number; entry_id?:number; program_number:number; horse_name:string|null; handicap_rating:number|null; agf_percent:number|null; weight_kg:number|null; win_probability?:number };
type Daily = { race_id:number; city:string; race_number:number; scheduled_time:string|null; chaos_index:number; top_entry:Entry };
type Health = { trained:boolean; deployed_model?:string; candidate_top1_accuracy?:number|null; handicap_benchmark_top1_accuracy?:number|null; decision?:string };
type FeaturedExplanation = { candidates:{entry_id:number; program_number:number; strengths:{label:string;detail:string}[]}[] };
const api='http://127.0.0.1:8042/api/v1';
async function getJson<T>(path:string, fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
const clean=(value:string|null|undefined)=>{let text=(value??"").replace(/\\u([0-9a-f]{4})/gi,(_,code)=>String.fromCharCode(parseInt(code,16)));for(let index=0;index<4;index+=1){if(!/[\u00c3\u00c2\u00e2]/.test(text))break;try{text=decodeURIComponent(escape(text))}catch{break}}return text;};
const key=(entry:Entry,index:number)=>`${entry.entry_id??entry.id??entry.program_number}-${index}`;
export const dynamic='force-dynamic';
export default async function Home(){
 const [allRaces,health]=await Promise.all([getJson<Race[]>('/races/',[]),getJson<Health>('/decision/model-health',{trained:false})]);
 const localToday=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const dates=[...new Set(allRaces.map(r=>r.race_date))].sort();
 const activeDate=dates.includes(localToday)?localToday:(dates.at(-1)??'');
 const races=allRaces.filter(r=>r.race_date===activeDate).sort((a,b)=>`${a.scheduled_time??''}-${a.track.city}`.localeCompare(`${b.scheduled_time??''}-${b.track.city}`));
 const cards=await Promise.all(races.map(async race=>({...race,entries:await getJson<Entry[]>(`/races/${race.id}/entries`,[])})));
 const daily=activeDate?await getJson<Daily[]>(`/races/daily-intelligence?race_date=${activeDate}`,[]):[];
 const dailyByRace=new Map(daily.map(item=>[item.race_id,item])); const featured=daily[0]; const runnerCount=cards.reduce((n,r)=>n+r.entries.length,0);
 const featuredExplanation=featured?await getJson<FeaturedExplanation|null>(`/explanations/races/${featured.race_id}`,null):null;
 const featuredSignals=featuredExplanation?.candidates.find(item=>item.program_number===featured?.top_entry.program_number)?.strengths.slice(0,2)??[];
 return <main className="dashboard-shell bright-dashboard">
  <header className="dashboard-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><nav><a href="#program">Program</a><a href="#model">Model</a></nav><div className="nav-meta"><span>{activeDate||'Tarih bekleniyor'}</span><b className={races.length?'live':'idle'}>{races.length?'CanlÄ± program':'Veri bekleniyor'}</b></div></header>
  <section className="welcome"><div><p className="eyebrow">BUGÃœNÃœN YARIÅ MASASI</p><h1>Net sinyal, sakin karar.</h1><p>BugÃ¼nÃ¼n resmi programÄ±nda <b>{races.length} koÅŸu</b> ve <b>{runnerCount} at</b> incelenmeye hazÄ±r. YarÄ±ÅŸ kartÄ±ndan adaylarÄ±, riski ve piyasa ayrÅŸmasÄ±nÄ± birlikte gÃ¶r.</p></div><aside className="today-highlight"><small>Ã–NE Ã‡IKAN KART</small>{featured?<><b>{clean(featured.city)} Â· {featured.race_number}. KoÅŸu</b><strong>{featured.top_entry.program_number}. {clean(featured.top_entry.horse_name)}</strong><span>%{featured.top_entry.win_probability?.toFixed(1)??'--'} model olasÄ±lÄ±ÄŸÄ±</span>{featuredSignals.length?<ul className="featured-signals">{featuredSignals.map((signal,index)=><li key={`${signal.label}-${index}`}>{signal.label}: {signal.detail}</li>)}</ul>:null}<a href={`/races/${featured.race_id}`}>KartÄ± aÃ§ â†’</a></>:<span>GÃ¼ncel analiz hesaplanÄ±yor.</span>}</aside></section>
  <section className="signal-row"><article><span>Aktif koÅŸu</span><strong>{races.length}</strong><small>{activeDate||'--'}</small></article><article><span>At giriÅŸi</span><strong>{runnerCount}</strong><small>BugÃ¼nÃ¼n kartlarÄ±</small></article><article><span>Hipodrom</span><strong>{new Set(races.map(r=>r.track.city)).size}</strong><small>{[...new Set(races.map(r=>clean(r.track.city)))].join(' Â· ')||'--'}</small></article><article><span>Model kontrolÃ¼</span><strong>{health.trained?'HazÄ±r':'Bekliyor'}</strong><small>{clean(health.decision)||health.deployed_model||'DoÄŸrulama yapÄ±lÄ±yor'}</small></article></section>
  <section className="workspace"><section className="panel race-board" id="program"><div className="panel-head"><div><p className="eyebrow">RESMÄ° GÃœNLÃœK PROGRAM</p><h2>BugÃ¼n hangi hipodromlarda koÅŸu var?</h2></div><span>{cards.length} kart</span></div>{cards.length?<div className="race-board-list">{cards.map(race=>{const intel=dailyByRace.get(race.id);return <a className="race-board-row" key={race.id} href={`/races/${race.id}`}><div className="race-time">{race.scheduled_time?.slice(0,5)??'--:--'}</div><div><b>{clean(race.track.city)} Â· {race.race_number}. KoÅŸu</b><small>{race.distance_meters}m Â· {clean(race.surface)} Â· {race.entries.length} at</small></div><div className="runner-preview">{race.entries.slice(0,2).map((e,i)=><span key={key(e,i)}>{e.program_number}. {clean(e.horse_name)}</span>)}</div><em>{intel?`Chaos ${intel.chaos_index}`:'KartÄ± incele'} â†’</em></a>})}</div>:<div className="empty">BugÃ¼n iÃ§in aktarÄ±lmÄ±ÅŸ koÅŸu bulunamadÄ±.</div>}</section><aside className="model-side" id="model"><article className="panel model-card"><p className="eyebrow">MODEL DURUMU</p><h2>{health.deployed_model??'Model bekleniyor'}</h2><div className="model-score">%{Math.round((health.candidate_top1_accuracy??0)*100)}</div><p>Zaman ayrÄ±mlÄ± testte birinci aday isabeti.</p><dl><div><dt>Model sonucu</dt><dd>{clean(health.decision)||'Kontrol ediliyor'}</dd></div><div><dt>Handikap referansÄ±</dt><dd>%{Math.round((health.handicap_benchmark_top1_accuracy??0)*100)}</dd></div></dl></article><article className="panel guide-card"><p className="eyebrow">KISA REHBER</p><ul><li><b>Chaos:</b> YarÄ±ÅŸ ne kadar belirsiz?</li><li><b>Value:</b> Model ve AGF nerede ayrÄ±ÅŸÄ±yor?</li><li><b>KoÅŸu kartÄ±:</b> AdaylarÄ± ve gerekÃ§eleri birlikte incele.</li></ul></article></aside></section>
 </main>
}