type Race={id:number;race_number:number;race_date:string;scheduled_time:string|null;distance_meters:number;surface:string;track:{name:string;city:string}};
type Entry={id?:number;entry_id?:number;program_number:number;horse_name:string|null;handicap_rating:number|null;agf_percent:number|null;weight_kg:number|null;win_probability?:number};
type Daily={race_id:number;city:string;race_number:number;scheduled_time:string|null;chaos_index:number;top_entry:Entry};
type Health={trained:boolean;deployed_model?:string;candidate_top1_accuracy?:number|null;handicap_benchmark_top1_accuracy?:number|null;decision?:string};
type Safety={state?:string;can_publish_actionable_scenarios?:boolean;reasons?:string[]};
type Explanation={candidates:{program_number:number;strengths:{label:string;detail:string}[]}[]};
type SourceStatus={ready:boolean;race_date:string|null;cities:{name:string;race_count:number}[];race_count:number;source_count:number;last_received_at:string|null};
type CurrentDayBoard={race_date?:string|null;ready?:boolean;source_count?:number;last_received_at?:string|null;cities?:string[];race_count?:number;races?:Race[]};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={live:'Canlı program',waiting:'Veri bekleniyor',stale:'Güncelleme bekliyor',source:'Resmi kaynak',todayDesk:'BUGÜNÜN YARIŞ MASASI',headline:'Net sinyal, sakin karar.',intro:'Bugünün resmi programında',races:'koşu',horses:'at',ready:'incelenmeye hazır. Yarış kartından adayları, riski ve piyasa ayrışmasını birlikte gör.',featured:'ÖNE ÇIKAN KART',probability:'model olasılığı',open:'Kartı aç →',active:'Aktif koşu',entries:'At girişi',tracks:'Hipodrom',model:'Model kontrolü',todayCards:'Bugünün kartları',readyText:'Hazır',daily:'RESMİ GÜNLÜK PROGRAM',where:'Bugün hangi hipodromlarda koşu var?',cards:'kart',empty:'Bugün için aktarılmış koşu bulunamadı.',review:'Kartı incele',modelStatus:'MODEL DURUMU',test:'Zaman ayrımlı testte birinci aday isabeti.',result:'Model sonucu',benchmark:'Handikap referansı',guide:'KISA REHBER',cityIstanbul:'İstanbul',cityIzmir:'İzmir',dot:'·',arrow:'→'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const response=await fetch(`${api}${path}`,{cache:'no-store'});return response.ok?await response.json() as T:fallback}catch{return fallback}}
function clean(value:string|null|undefined){let text=(value??'').replace(/\\u([0-9a-f]{4})/gi,(_,code)=>String.fromCharCode(parseInt(code,16)));for(let i=0;i<4;i+=1){if(!/[ÃÂâ]/.test(text))break;try{text=decodeURIComponent(escape(text))}catch{break}}return text}
function city(value:string){
 const name=clean(value);
 const labels:Record<string,string>={
  Istanbul:t.cityIstanbul,
  Izmir:t.cityIzmir,
  Elazig:'Elazığ',
  Diyarbakir:'Diyarbakır'
 };
 return labels[name]??name
}
const entryKey=(entry:Entry,index:number)=>`${entry.entry_id??entry.id??entry.program_number}-${index}`;
export const dynamic='force-dynamic';
export default async function Home(){
 const localToday=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const [board,health,safety]=await Promise.all([getJson<CurrentDayBoard>(`/analytics/current-day-board?race_date=${localToday}`,{race_date:null,ready:false,races:[],source_count:0,cities:[]}),getJson<Health>('/decision/model-health',{trained:false}),getJson<Safety>('/analytics/model-safety',{state:'review',can_publish_actionable_scenarios:false})]);
 const activeDate=String(board.race_date??'');
 const races=(board.races??[]).sort((a,b)=>`${a.scheduled_time??''}-${a.track.city}`.localeCompare(`${b.scheduled_time??''}-${b.track.city}`));
 const currentProgramReady=Boolean(board.ready)&&activeDate===localToday&&races.length>0;
 const safetyMessage=safety.state==='blocked'?'Do\u011frulanm\u0131\u015f sonu\u00e7 seti haz\u0131rlan\u0131yor':safety.state==='review'?'Kalibrasyon incelemesi s\u00fcr\u00fcyor':safety.can_publish_actionable_scenarios?'Model kontrol\u00fc tamamland\u0131':'Veri durumu bekleniyor';
 const safetyDetail=String((safety.reasons??[])[0]??(safety as {reason?:string}).reason??'');
 const sourceStatus:SourceStatus={ready:Boolean(board.ready),race_date:board.race_date??null,cities:(board.cities??[]).map(name=>({name,race_count:0})),race_count:Number(board.race_count??races.length),source_count:Number(board.source_count??0),last_received_at:board.last_received_at??null}; const cards=await Promise.all(races.map(async race=>({...race,entries:await getJson<Entry[]>(`/races/${race.id}/entries`,[])})));
 const daily=activeDate?await getJson<Daily[]>(`/races/daily-intelligence?race_date=${activeDate}`,[]):[];
 const dailyByRace=new Map(daily.map(item=>[item.race_id,item]));
 const featured=daily[0];
 const featuredExplanation=featured?await getJson<Explanation|null>(`/explanations/races/${featured.race_id}`,null):null;
 const featuredSignals=featuredExplanation?.candidates.find(item=>item.program_number===featured?.top_entry.program_number)?.strengths.slice(0,2)??[];
 const runnerCount=cards.reduce((total,card)=>total+card.entries.length,0);
 return <main className="dashboard-shell bright-dashboard">
  <header className="dashboard-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><nav><a href="/bulletin">{'Bülten'}</a><a href="/program">Program</a><a href="/shortlist">{'Kısa Liste'}</a><a href="/decision-center">Karar Merkezi</a><a href="/decision">Plan</a><a href="/coverage">Kapsam</a><a href="/model">Model</a><a href="/monitoring">{'İzleme'}</a><a href="/performance">Performans</a><a href="/data-health">Veri</a><a href="/quality-control">Kontrol</a></nav><div className="nav-meta"><span>{activeDate||'--'}</span><b className={currentProgramReady&&sourceStatus.ready?'live':'idle'}>{currentProgramReady&&sourceStatus.ready?t.live:t.stale}</b><small>{sourceStatus.ready?`${t.source}: ${sourceStatus.source_count}`:t.stale}</small></div></header>
  <section className="welcome"><div><p className="eyebrow">{t.todayDesk}</p><h1>{t.headline}</h1><p>{t.intro} <b>{races.length} {t.races}</b> {t.horses} <b>{runnerCount} {t.horses}</b> {t.ready}</p></div><aside className="today-highlight"><small>{t.featured}</small>{featured&&safety.can_publish_actionable_scenarios?<><b>{city(featured.city)} {t.dot} {featured.race_number}. {t.races}</b><strong>{featured.top_entry.program_number}. {clean(featured.top_entry.horse_name)}</strong><span>%{featured.top_entry.win_probability?.toFixed(1)??'--'} {t.probability}</span>{featuredSignals.length?<ul className="featured-signals">{featuredSignals.map((signal,index)=><li key={`${signal.label}-${index}`}>{clean(signal.label)}: {clean(signal.detail)}</li>)}</ul>:null}<a href={`/races/${featured.race_id}`}>{t.open}</a></>:<span>{safetyMessage}</span>}</aside></section>
  <section className="signal-row"><article><span>{t.active}</span><strong>{races.length}</strong><small>{activeDate||'--'}</small></article><article><span>{t.entries}</span><strong>{runnerCount}</strong><small>{t.todayCards}</small></article><article><span>{t.tracks}</span><strong>{new Set(races.map(race=>race.track.city)).size}</strong><small>{[...new Set(races.map(race=>city(race.track.city)))].join(' · ')||'--'}</small></article><article><span>{t.model}</span><strong>{safety.can_publish_actionable_scenarios?(health.trained?t.readyText:t.waiting):safetyMessage}</strong><small>{safety.can_publish_actionable_scenarios?(clean(health.decision)||health.deployed_model||t.waiting):(safetyDetail||safetyMessage)}</small></article></section>
  <section className="workspace"><section className="panel race-board" id="program"><div className="panel-head"><div><p className="eyebrow">{t.daily}</p><h2>{t.where}</h2></div><span>{cards.length} {t.cards}</span></div>{cards.length?<div className="race-board-list">{cards.map(race=>{const intelligence=dailyByRace.get(race.id);return <a className="race-board-row" key={race.id} href={`/races/${race.id}`}><div className="race-time">{race.scheduled_time?.slice(0,5)??'--:--'}</div><div><b>{city(race.track.city)} {t.dot} {race.race_number}. {t.races}</b><small>{race.distance_meters}m {t.dot} {clean(race.surface)} {t.dot} {race.entries.length} {t.horses}</small></div><div className="runner-preview">{race.entries.slice(0,2).map((entry,index)=><span key={entryKey(entry,index)}>{entry.program_number}. {clean(entry.horse_name)}</span>)}</div><em>{intelligence?`Chaos ${intelligence.chaos_index}`:t.review} {t.arrow}</em></a>})}</div>:<div className="empty">{t.empty}</div>}</section><aside className="model-side" id="model"><article className="panel model-card"><p className="eyebrow">{t.modelStatus}</p><h2>{health.deployed_model??t.waiting}</h2><div className="model-score">{safety.can_publish_actionable_scenarios?("%"+Math.round((health.candidate_top1_accuracy??0)*100)):"--"}</div><p>{safety.can_publish_actionable_scenarios?t.test:'Kalibrasyon ve resmi sonu\u00e7 kontrolleri tamamlanana kadar metrik yay\u0131nlanmaz.'}</p><dl><div><dt>{t.result}</dt><dd>{safety.can_publish_actionable_scenarios?(clean(health.decision)||t.waiting):'Model review'}</dd></div><div><dt>{t.benchmark}</dt><dd>%{Math.round((health.handicap_benchmark_top1_accuracy??0)*100)}</dd></div></dl></article><article className="panel guide-card"><p className="eyebrow">{t.guide}</p><ul><li><b>Chaos:</b> {clean('Yarış ne kadar belirsiz?')}</li><li><b>Value:</b> {clean('Model ve AGF nerede ayrışıyor?')}</li><li><b>{t.races}:</b> {clean('Adayları ve gerekçeleri birlikte incele.')}</li></ul></article></aside></section>
 </main>
}