type Safety={state:string;can_publish_actionable_scenarios:boolean;reason?:string;metrics?:{settled_races?:number;calibration_gap?:number|null;model_top1?:number|null;benchmark_top1?:number|null}};
type Calibration={selected_shrinkage:number;tune_races:number;holdout_races:number;raw_holdout_brier:number;candidate_holdout_brier:number;raw_holdout_top1:number;candidate_holdout_top1:number;eligible_for_manual_promotion:boolean;note:string};
type Audit={audited_races:number;skipped_races:number;top1_accuracy:number|null;top3_coverage:number|null;eligibility:string;note:string;calibration_bands:{band:string;entries:number;average_probability:number;actual_win_rate:number}[]};
type Daily={ready:boolean;race_date:string|null;race_count:number;source_count:number;last_received_at:string|null;cities:{name:string;race_count:number}[]};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'← Programa dön',tag:'KALİTE KONTROLÜ',title:'Yayın kararı: veri, model ve sonuç birlikte.',lead:'Bu ekran bir tahmin vitrini değil; Pegasus’un hangi bilgiyi ne kadar sağlam bildiğini denetlemek içindir.',daily:'Günlük kaynak',safety:'Yayın güvenliği',calibration:'Kalibrasyon testi',audit:'Geçmiş tahmin denetimi',ready:'Doğrulandı',waiting:'Eksik / inceleniyor',pass:'Manuel inceleme eşiğini geçti',hold:'Yayına alınmadı',brier:'Brier',top1:'Birinci aday',top3:'İlk üç kapsama',source:'Resmi kaynak kaydı',races:'koşu',auditNote:'Sadece resmi sonuç kaydından önce oluşturulmuş tahminler sayılır.',warning:'Bu metrikler bahis, getiri veya kesin sonuç vaadi değildir.'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
const pct=(value:number|null|undefined)=>value==null?'--':`%${(Number(value)*100).toFixed(1)}`;
export const dynamic='force-dynamic';
export default async function QualityControl(){
 const [daily,safety,calibration,audit]=await Promise.all([
  getJson<Daily>('/analytics/daily-program-status',{ready:false,race_date:null,race_count:0,source_count:0,last_received_at:null,cities:[]}),
  getJson<Safety>('/analytics/model-safety',{state:'unknown',can_publish_actionable_scenarios:false}),
  getJson<Calibration|null>('/ml/calibration-promotion',null),
  getJson<Audit>('/analytics/recommendation-outcome-audit',{audited_races:0,skipped_races:0,top1_accuracy:null,top3_coverage:null,eligibility:'unknown',note:'',calibration_bands:[]}),
 ]);
 const isReady=daily.ready&&safety.can_publish_actionable_scenarios;
 return <main className="data-shell"><header className="data-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><div><a href="/daily-readiness">{'Günlük kontrol'}</a> <a href="/">{t.back}</a></div></header><section className="data-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="data-metrics"><article><span>{t.daily}</span><strong>{daily.ready?t.ready:t.waiting}</strong><small>{daily.race_date??'--'} {'·'} {daily.race_count} {t.races}</small></article><article><span>{t.safety}</span><strong>{safety.state}</strong><small>{isReady?t.ready:t.waiting}</small></article><article><span>{t.calibration}</span><strong>{calibration?.eligible_for_manual_promotion?t.pass:t.hold}</strong><small>{calibration?`${calibration.holdout_races} ${t.races}`:'--'}</small></article><article><span>{t.audit}</span><strong>{audit.audited_races}</strong><small>{audit.eligibility}</small></article></section><section className="data-grid"><article className="data-panel"><p className="eyebrow">{t.source}</p><h2>{daily.ready?t.ready:t.waiting}</h2><p>{daily.cities.map(item=>`${item.name} (${item.race_count})`).join(' · ')||'--'}</p><dl><div><dt>{t.races}</dt><dd>{daily.race_count}</dd></div><div><dt>Kaynak</dt><dd>{daily.source_count}</dd></div></dl></article><article className="data-panel"><p className="eyebrow">{t.calibration}</p>{calibration?<><h2>{calibration.eligible_for_manual_promotion?t.pass:t.hold}</h2><dl><div><dt>{t.brier}</dt><dd>{calibration.raw_holdout_brier.toFixed(4)} {'→'} {calibration.candidate_holdout_brier.toFixed(4)}</dd></div><div><dt>{t.top1}</dt><dd>{pct(calibration.raw_holdout_top1)} {'→'} {pct(calibration.candidate_holdout_top1)}</dd></div></dl></>:<p>{t.waiting}</p>}</article><article className="data-panel"><p className="eyebrow">{t.audit}</p><h2>{audit.audited_races?`${audit.audited_races} ${t.races}`:t.waiting}</h2><dl><div><dt>{t.top1}</dt><dd>{pct(audit.top1_accuracy)}</dd></div><div><dt>{t.top3}</dt><dd>{pct(audit.top3_coverage)}</dd></div></dl><small>{t.auditNote}</small></article></section><p className="disclaimer">{safety.reason??audit.note??t.warning}<br/>{t.warning}</p></main>
}