type Period={evaluated_races:number;top1_accuracy:number|null;top3_coverage:number|null;model_versions:Record<string,number>};
type Monitor={window:number;recent:Period;previous:Period;top1_change_points:number|null;state:string;note:string};
type Slice={name:string;evaluated_races:number;top1_accuracy:number|null;top3_coverage:number|null};
type Slices={window:number;by_city:Slice[];by_surface:Slice[];note:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const tr={back:'Programa d\u00f6n',tag:'MODEL \u0130ZLEME',title:'Modelin nabz\u0131',intro:'Son sonu\u00e7lanm\u0131\u015f yar\u0131\u015flar \u00fczerinden model performans\u0131n\u0131 iki d\u00f6nemde izle.',recent:'Son d\u00f6nem',previous:'\u00d6nceki d\u00f6nem',top1:'Birinci aday',top3:'\u0130lk 3 kapsama',races:'De\u011ferlendirilen yar\u0131\u015f',change:'Top-1 de\u011fi\u015fimi',improving:'\u0130yile\u015fiyor',review:'\u0130nceleme gerekli',watch:'\u0130zleniyor',slices:'KO\u015eUL BAZINDA OKUMA',city:'Hipodrom',surface:'Pist tipi',sample:'\u00d6rneklem',note:'Bu ekran olas\u0131l\u0131k kalitesini izler; getiri veya kesin sonu\u00e7 vaadi vermez.'};
function fmt(value:number|null){return value===null?'--':'%'+value.toFixed(1)}
function city(value:string){const labels:Record<string,string>={Istanbul:'\u0130stanbul',Izmir:'\u0130zmir',Elazig:'Elaz\u0131\u011f',Diyarbakir:'Diyarbak\u0131r'};return labels[value]??value}
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const response=await fetch(api+path,{cache:'no-store'});return response.ok?await response.json() as T:fallback}catch{return fallback}}
export const dynamic='force-dynamic';
function SliceTable({title,items}:{title:string;items:Slice[]}){return <article className="panel model-card"><p className="eyebrow">{title}</p>{items.length?<div className="slice-list">{items.map(item=><div className="slice-row" key={item.name}><b>{city(item.name)}</b><span>{fmt(item.top1_accuracy)} {tr.top1}</span><small>{item.evaluated_races} {tr.races}</small></div>)}</div>:<p>Yeterli sonu\u00e7 kayd\u0131 yok.</p>}</article>}
export default async function Monitoring(){const [data,slices]=await Promise.all([getJson<Monitor|null>('/analytics/model-monitor?window=60',null),getJson<Slices>('/analytics/model-monitor/slices?window=240',{window:240,by_city:[],by_surface:[],note:''})]);const state=data?.state??'watch';const title=state==='improving'?tr.improving:state==='review'?tr.review:tr.watch;return <main className="dashboard-shell bright-dashboard"><header className="dashboard-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><nav><a href="/">{tr.back}</a><a href="/model">Model</a><a href="/performance">Performans</a></nav></header><section className="welcome"><div><p className="eyebrow">{tr.tag}</p><h1>{tr.title}</h1><p>{tr.intro}</p></div><aside className="today-highlight"><small>{tr.change}</small><strong>{data?.top1_change_points===null||data?.top1_change_points===undefined?'--':(data.top1_change_points>0?'+':'')+data.top1_change_points+' puan'}</strong><b>{title}</b></aside></section>{data?<><section className="signal-row"><article><span>{tr.recent+' '+tr.top1}</span><strong>{fmt(data.recent.top1_accuracy)}</strong><small>{data.recent.evaluated_races} {tr.races}</small></article><article><span>{tr.recent+' '+tr.top3}</span><strong>{fmt(data.recent.top3_coverage)}</strong><small>{data.window} yar\u0131\u015fl\u0131k pencere</small></article><article><span>{tr.previous+' '+tr.top1}</span><strong>{fmt(data.previous.top1_accuracy)}</strong><small>{data.previous.evaluated_races} {tr.races}</small></article><article><span>Model s\u00fcr\u00fcm\u00fc</span><strong>{Object.keys(data.recent.model_versions)[0]??'--'}</strong><small>{tr.note}</small></article></section><section className="workspace"><section className="panel race-board"><div className="panel-head"><div><p className="eyebrow">{tr.slices}</p><h2>Model nerede daha tutarl\u0131?</h2></div><span>{slices.window} {tr.races}</span></div><div className="data-grid"><SliceTable title={tr.city} items={slices.by_city}/><SliceTable title={tr.surface} items={slices.by_surface}/></div></section></section></>:<section className="panel empty">\u0130zleme verisi hen\u00fcz haz\u0131r de\u011fil.</section>}</main>}