type Period={evaluated_races:number;top1_accuracy:number|null;top3_coverage:number|null;model_versions:Record<string,number>};
type Monitor={window:number;recent:Period;previous:Period;top1_change_points:number|null;state:string;note:string};
type Slice={name:string;evaluated_races:number;top1_accuracy:number|null;top3_coverage:number|null};
type Slices={window:number;by_city:Slice[];by_surface:Slice[];note:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const tr={back:'Programa dön',tag:'MODEL İZLEME',title:'Modelin nabzı',intro:'Son sonuçlanmış yarışlar üzerinden model performansını iki dönemde izle.',recent:'Son dönem',previous:'Önceki dönem',top1:'Birinci aday',top3:'İlk 3 kapsama',races:'Değerlendirilen yarış',change:'Top-1 değişimi',improving:'İyileşiyor',review:'İnceleme gerekli',watch:'İzleniyor',slices:'KOŞUL BAZINDA OKUMA',city:'Hipodrom',surface:'Pist tipi',sample:'Örneklem',note:'Bu ekran olasılık kalitesini izler; getiri veya kesin sonuç vaadi vermez.'};
function fmt(value:number|null){return value===null?'--':'%'+value.toFixed(1)}
function city(value:string){const labels:Record<string,string>={Istanbul:'İstanbul',Izmir:'İzmir',Elazig:'Elazığ',Diyarbakir:'Diyarbakır'};return labels[value]??value}
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const response=await fetch(api+path,{cache:'no-store'});return response.ok?await response.json() as T:fallback}catch{return fallback}}
export const dynamic='force-dynamic';
function SliceTable({title,items}:{title:string;items:Slice[]}){return <article className="panel model-card"><p className="eyebrow">{title}</p>{items.length?<div className="slice-list">{items.map(item=><div className="slice-row" key={item.name}><b>{city(item.name)}</b><span>{fmt(item.top1_accuracy)} {tr.top1}</span><small>{item.evaluated_races} {tr.races}</small></div>)}</div>:<p>Yeterli sonuç kaydı yok.</p>}</article>}
export default async function Monitoring(){const [data,slices]=await Promise.all([getJson<Monitor|null>('/analytics/model-monitor?window=60',null),getJson<Slices>('/analytics/model-monitor/slices?window=240',{window:240,by_city:[],by_surface:[],note:''})]);const state=data?.state??'watch';const title=state==='improving'?tr.improving:state==='review'?tr.review:tr.watch;return <main className="dashboard-shell bright-dashboard"><header className="dashboard-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><nav><a href="/">{tr.back}</a><a href="/model">Model</a><a href="/performance">Performans</a></nav></header><section className="welcome"><div><p className="eyebrow">{tr.tag}</p><h1>{tr.title}</h1><p>{tr.intro}</p></div><aside className="today-highlight"><small>{tr.change}</small><strong>{data?.top1_change_points===null||data?.top1_change_points===undefined?'--':(data.top1_change_points>0?'+':'')+data.top1_change_points+' puan'}</strong><b>{title}</b></aside></section>{data?<><section className="signal-row"><article><span>{tr.recent+' '+tr.top1}</span><strong>{fmt(data.recent.top1_accuracy)}</strong><small>{data.recent.evaluated_races} {tr.races}</small></article><article><span>{tr.recent+' '+tr.top3}</span><strong>{fmt(data.recent.top3_coverage)}</strong><small>{data.window} yarışlık pencere</small></article><article><span>{tr.previous+' '+tr.top1}</span><strong>{fmt(data.previous.top1_accuracy)}</strong><small>{data.previous.evaluated_races} {tr.races}</small></article><article><span>Model sürümü</span><strong>{Object.keys(data.recent.model_versions)[0]??'--'}</strong><small>{tr.note}</small></article></section><section className="workspace"><section className="panel race-board"><div className="panel-head"><div><p className="eyebrow">{tr.slices}</p><h2>Model nerede daha tutarlı?</h2></div><span>{slices.window} {tr.races}</span></div><div className="data-grid"><SliceTable title={tr.city} items={slices.by_city}/><SliceTable title={tr.surface} items={slices.by_surface}/></div></section></section></>:<section className="panel empty">İzleme verisi henüz hazır değil.</section>}</main>}