type Race={id:number;race_number:number;race_date:string;scheduled_time:string|null;track:{city:string}};
type Entry={program_number:number;horse_name:string|null;win_probability?:number|string|null;agf_percent?:number|string|null};
type Recommendation={race_id:number;race_number:number;city?:string;chaos_index?:number|string|null;confidence?:string;primary:Entry;alternatives:Entry[];reasons:string[];model_version?:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Programa d\u00f6n',tag:'G\u00dcNL\u00dcK KARAR PLANI',title:'Kapsam\u0131 netle\u015ftir, riski g\u00f6r.',lead:'Bu ekran, g\u00fcn\u00fcn program\u0131ndaki model adaylar\u0131n\u0131 bir araya getirir. Kesin sonu\u00e7 vaadi de\u011fil, karar deste\u011fi sunar.',empty:'Bug\u00fcn i\u00e7in model \u00f6nerisi hen\u00fcz olu\u015fmad\u0131.',plan:'DENGEL\u0130 KAPSAM',primary:'Birinci aday',alternatives:'Alternatifler',risk:'Risk',why:'Model gerek\u00e7eleri',open:'Kart\u0131 a\u00e7 \u2192',high:'Y\u00fcksek',medium:'Orta',low:'D\u00fc\u015f\u00fck',cards:'kart',race:'ko\u015fu',dot:'\u00b7'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function num(value:unknown){const n=typeof value==='number'?value:Number(String(value??'').replace(',','.'));return Number.isFinite(n)?n:null}
function one(value:unknown){const n=num(value);return n==null?'--':n.toFixed(1)}
function clean(value:string|null|undefined){let s=(value??'').replace(/\\u([0-9a-f]{4})/gi,(_,c)=>String.fromCharCode(parseInt(c,16)));for(let i=0;i<4;i+=1){if(!/[\u00c3\u00c2\u00e2]/.test(s))break;try{s=decodeURIComponent(escape(s))}catch{break}}return s}
function city(value:string|undefined){const x=clean(value);return x==='Istanbul'?'\u0130stanbul':x==='Izmir'?'\u0130zmir':x}
function risk(value:unknown){const n=num(value)??0;return n>=70?t.high:n>=40?t.medium:t.low}
export const dynamic='force-dynamic';
export default async function DecisionPage(){const races=await getJson<Race[]>('/races/',[]);const dates=[...new Set(races.map(r=>r.race_date))].sort();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());const date=dates.includes(today)?today:(dates.at(-1)??'');const dayRaces=races.filter(r=>r.race_date===date);const recs=await getJson<Recommendation[]>(`/recommendations/daily?race_date=${date}`,[]);const raceById=new Map(dayRaces.map(r=>[r.id,r]));const cards=recs.filter(r=>raceById.has(r.race_id)).sort((a,b)=>(num(a.chaos_index)??100)-(num(b.chaos_index)??100));return <main className="decision-shell"><header className="decision-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="decision-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="decision-summary"><article><span>{date||'--'}</span><strong>{cards.length}</strong><small>{t.cards}</small></article><article><span>{t.plan}</span><strong>{cards.filter(c=>(num(c.chaos_index)??100)<55).length}</strong><small>{t.low} / {t.medium} {t.risk}</small></article></section>{cards.length?<section className="decision-list">{cards.map(rec=>{const race=raceById.get(rec.race_id)!;return <article className="decision-card" key={rec.race_id}><div className="decision-card-head"><div><p>{city(race.track.city)} {t.dot} {race.race_number}. {t.race}</p><span>{race.scheduled_time?.slice(0,5)??'--:--'} {t.dot} {t.risk}: {risk(rec.chaos_index)}</span></div><b>Chaos {one(rec.chaos_index)}</b></div><div className="decision-primary"><small>{t.primary}</small><h2>{rec.primary.program_number}. {clean(rec.primary.horse_name)}</h2><strong>%{one(rec.primary.win_probability)}</strong></div><div className="decision-alts"><b>{t.alternatives}</b><span>{rec.alternatives.slice(0,3).map(item=>`${item.program_number}. ${clean(item.horse_name)}`).join(` ${t.dot} `)||'--'}</span></div><ul>{rec.reasons.slice(0,2).map((item,index)=><li key={`${item}-${index}`}>{clean(item)}</li>)}</ul><a href={`/races/${rec.race_id}`}>{t.open}</a></article>})}</section>:<div className="decision-empty">{t.empty}</div>}</main>}