type Readiness={race_count:number;entry_count:number;result_count?:number;result_row_count?:number;prediction_snapshot_count?:number;prediction_snapshot_row_count?:number;races_with_two_or_more_entries:number;result_coverage_percent:number;date_range:{from:string|null;to:string|null};baseline_ready:boolean;ml_training_ready:boolean;note?:string};
type City={name:string;race_count:number};
type DailyStatus={ready:boolean;race_date:string|null;cities:City[];race_count:number;source_count:number;last_received_at:string|null};
type CoverageRace={race_id:number;city:string|null;race_number:number;entry_count:number;coverage_percent:number;missing:Record<string,number>;state:string};
type Coverage={race_date:string|null;race_count:number;coverage_percent:number;ready_races:number;review_races:number;limited_races:number;races:CoverageRace[];note:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'← Programa dön',tag:'VERİ SAĞLIĞI',title:'Modelin yakıtı: doğru, güncel ve izlenebilir veri.',lead:'Bu ekran yarış, at girişi, sonuç, tahmin kaydı ve model girdilerinin kapsamasını birlikte gösterir.',races:'Yarış kaydı',entries:'At girişi',results:'Resmî sonuç',snapshots:'Tahmin kaydı',coverage:'Sonuç kapsamı',inputCoverage:'Model girdi kapsamı',range:'Veri aralığı',quality:'KALİTE KONTROLÜ',ready:'Model eğitimine uygun',waiting:'Veri eşiği bekleniyor',cards:'Yeterli katılımcısı olan koşu',note:'Eksik veya geç gelen resmî kayıtlar, olumlu bir model sinyali olarak yorumlanmaz.',daily:'GÜNLÜK PROGRAM DURUMU',official:'Resmî TJK kaynak kaydı',received:'Son alım',cities:'Aktif hipodromlar',noDaily:'Günlük program henüz doğrulanmadı.',inputs:'MODEL GİRDİLERİ',readyCards:'Yeterli girdi',reviewCards:'Kontrol gerektiren',limitedCards:'Sınırlı veri'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function city(value:string){const labels:Record<string,string>={Istanbul:'İstanbul',Izmir:'İzmir',Elazig:'Elazığ',Diyarbakir:'Diyarbakır'};return labels[value]??value}
export const dynamic='force-dynamic';
export default async function DataHealth(){const [d,daily,inputCoverage]=await Promise.all([getJson<Readiness>('/analytics/model-readiness',{race_count:0,entry_count:0,result_count:0,races_with_two_or_more_entries:0,result_coverage_percent:0,date_range:{from:null,to:null},baseline_ready:false,ml_training_ready:false}),getJson<DailyStatus>('/analytics/daily-program-status',{ready:false,race_date:null,cities:[],race_count:0,source_count:0,last_received_at:null}),getJson<Coverage>('/analytics/model-input-coverage',{race_date:null,race_count:0,coverage_percent:0,ready_races:0,review_races:0,limited_races:0,races:[],note:''})]);const results=d.result_count??d.result_row_count??0;const snapshots=d.prediction_snapshot_count??d.prediction_snapshot_row_count??0;return <main className="data-shell"><header className="data-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="data-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="data-metrics"><article><span>{t.races}</span><strong>{d.race_count}</strong></article><article><span>{t.entries}</span><strong>{d.entry_count}</strong></article><article><span>{t.results}</span><strong>{results}</strong></article><article><span>{t.snapshots}</span><strong>{snapshots}</strong></article><article><span>{t.inputCoverage}</span><strong>%{Number(inputCoverage.coverage_percent??0).toFixed(1)}</strong></article></section><section className="data-grid"><article className="data-panel"><p className="eyebrow">{t.quality}</p><div className="quality-score"><strong>%{Number(d.result_coverage_percent??0).toFixed(1)}</strong><span>{t.coverage}</span></div><dl><div><dt>{t.cards}</dt><dd>{d.races_with_two_or_more_entries}</dd></div><div><dt>{t.range}</dt><dd>{d.date_range.from??'--'} - {d.date_range.to??'--'}</dd></div></dl></article><article className="data-panel"><p className="eyebrow">MODEL HAZIRLIĞI</p><h2>{d.ml_training_ready?t.ready:t.waiting}</h2><p>{d.note??t.note}</p><small>{t.note}</small></article><article className="data-panel"><p className="eyebrow">{t.daily}</p>{daily.ready?<><h2>{daily.race_date}</h2><p>{daily.cities.map(item=>`${city(item.name)} (${item.race_count})`).join(' · ')}</p><dl><div><dt>{t.official}</dt><dd>{daily.source_count}</dd></div><div><dt>{t.received}</dt><dd>{daily.last_received_at??'--'}</dd></div></dl></>:<p>{t.noDaily}</p>}</article></section><section className="data-panel"><p className="eyebrow">{t.inputs}</p><h2>%{Number(inputCoverage.coverage_percent??0).toFixed(1)}</h2><p>{inputCoverage.note}</p><dl><div><dt>{t.readyCards}</dt><dd>{inputCoverage.ready_races}</dd></div><div><dt>{t.reviewCards}</dt><dd>{inputCoverage.review_races}</dd></div><div><dt>{t.limitedCards}</dt><dd>{inputCoverage.limited_races}</dd></div></dl></section></main>}