type Race={id:number;race_number:number;scheduled_time?:string|null;start_time?:string|null;distance_meters?:number|null;surface?:string|null;race_class?:string|null;track?:{name?:string|null;city?:string|null}|null};
type Entry={id:number;program_number?:number|null;horse_id?:number|null;horse_name?:string|null;jockey_name?:string|null;trainer_name?:string|null;weight_kg?:number|string|null;handicap_rating?:number|string|null;agf_percent?:number|string|null};
type Safety={can_publish_actionable_scenarios?:boolean;state?:string;verified_race_dates?:number;minimum_race_dates?:number};
export const dynamic='force-dynamic';
const api=process.env.PEGASUS_API_URL || process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8042/api/v1';
const t={title:'Yarış günü masası',intro:'Resmî programı hipodrom, koşu ve katılımcı bazında tek ekranda incele.',back:'Ana ekrana dön',city:'Hipodrom',race:'Koşu',card:'Koşu kartı',runners:'at',no:'No',horse:'At',hp:'HP',weight:'Kilo',jockey:'Jokey',trainer:'Antrenör',agf:'AGF',profile:'Profil',review:'Model inceleme modunda',safe:'Doğrulanmış sonuç ve kalibrasyon eşiği tamamlanmadan aday ve kupon içeriği gösterilmez.',empty:'Bugün için aktarılmış resmî program bulunamadı.',source:'Resmî program aktarımı',dot:'·'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function list<T>(value:unknown):T[]{if(Array.isArray(value))return value as T[];const o=value as {items?:T[];races?:T[]};return o.items||o.races||[]}
function text(value:unknown){return value===null||value===undefined||value===''?'--':String(value)}
function time(race:Race){return text(race.scheduled_time??race.start_time).slice(0,5)}
function city(race:Race){const value=text(race.track?.city??race.track?.name);return value==='Istanbul'?'İstanbul':value==='Izmir'?'İzmir':value==='Elazig'?'Elazığ':value==='Diyarbakir'?'Diyarbakır':value}
function percent(value:unknown){const n=Number(value);return Number.isFinite(n)?`%${n.toFixed(1)}`:'--'}
export default async function RaceDay({searchParams}:{searchParams:Promise<{city?:string;race?:string}>}){
 const query=await searchParams; const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const [board,safety]=await Promise.all([getJson<{races?:Race[]}>(`/analytics/current-day-board?race_date=${today}`,{races:[]}),getJson<Safety>('/analytics/model-safety',{can_publish_actionable_scenarios:false,state:'review'})]);
 const races=list<Race>(board.races); const cities=Array.from(new Set(races.map(city).filter(x=>x!=='--'))).sort((a,b)=>a.localeCompare(b,'tr')); const chosen=cities.includes(query.city??'')?String(query.city):cities[0]??'';
 const cityRaces=races.filter(race=>city(race)===chosen).sort((a,b)=>(a.race_number??999)-(b.race_number??999)); const selected=cityRaces.find(race=>race.id===Number(query.race))??cityRaces[0]??null;
 const entries=selected?list<Entry>(await getJson<unknown>(`/races/${selected.id}/entries`,[])).sort((a,b)=>(a.program_number??999)-(b.program_number??999)):[];
 const href=(name:string,id?:number)=>`/race-day?city=${encodeURIComponent(name)}${id?`&race=${id}`:''}`;
 return <main className="race-day-shell"><header className="race-day-nav"><a className="race-day-brand" href="/"><span>{String.fromCharCode(0x265E)}</span><b>PEGASUS</b><small>RACE INTELLIGENCE</small></a><nav><a href="/bulletin">{'Bülten'}</a><a href="/program">Program</a><a className="active" href="/race-day">{'Yarış Günü'}</a></nav><a href="/">{t.back}</a></header><section className="race-day-hero"><div><p className="eyebrow">{today}</p><h1>{t.title}</h1><p>{t.intro}</p></div><aside><b>{races.length} {t.race}</b><span>{cities.length} {t.city.toLowerCase()}</span><small>{t.source}</small></aside></section>{!selected?<section className="race-day-empty">{t.empty}</section>:<><nav className="race-day-cities" aria-label={t.city}>{cities.map(name=><a key={name} className={name===chosen?'active':''} href={href(name)}>{name}</a>)}</nav><nav className="race-day-races" aria-label={t.race}>{cityRaces.map(race=><a key={race.id} className={race.id===selected.id?'active':''} href={href(chosen,race.id)}><b>{race.race_number}. {t.race}</b><span>{time(race)}</span></a>)}</nav><section className="race-day-card"><div className="race-day-card-head"><div className="race-day-mark">{String.fromCharCode(0x265E)}</div><div><p className="eyebrow">{chosen} {t.dot} {selected.race_number}. {t.race}</p><h2>{time(selected)} {t.dot} {selected.distance_meters??'--'}m {t.dot} {text(selected.surface)}</h2><p>{text(selected.race_class)}</p></div><a href={`/races/${selected.id}`}>{t.card} {String.fromCharCode(0x2192)}</a></div>{!safety.can_publish_actionable_scenarios?<div className="race-day-safety"><b>{t.review}</b><span>{t.safe}</span><small>{safety.verified_race_dates??0}/{safety.minimum_race_dates??20} {'doğrulanmış gün'}</small></div>:null}<div className="race-day-table-wrap"><table><thead><tr><th>{t.no}</th><th>{t.horse}</th><th>{t.hp}</th><th>{t.weight}</th><th>{t.jockey}</th><th>{t.trainer}</th><th>{t.agf}</th></tr></thead><tbody>{entries.map(entry=><tr key={entry.id}><td>{text(entry.program_number)}</td><td>{entry.horse_id?<a href={`/horses/${entry.horse_id}`}>{text(entry.horse_name)}<small>{t.profile} {String.fromCharCode(0x2192)}</small></a>:text(entry.horse_name)}</td><td>{text(entry.handicap_rating)}</td><td>{text(entry.weight_kg)}</td><td>{text(entry.jockey_name)}</td><td>{text(entry.trainer_name)}</td><td>{percent(entry.agf_percent)}</td></tr>)}</tbody></table></div></section></>}</main>
}