type Item={race_id:number;race_date:string;city:string;race_number:number;surface:string;distance_meters:number;program_number:number;handicap_rating:number|null;weight_kg:number|null;finish_position:number|null;won:boolean};
type Profile={horse:{id:number;name:string;country:string|null;birth_year:number|null;gender:string|null;father:string|null;mother:string|null};summary:{settled_starts:number;wins:number;top3_finishes:number;win_rate:number|null;top3_rate:number|null};history:Item[]};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Programa d\u00f6n',tag:'AT PROF\u0130L\u0130',starts:'Sonu\u00e7lanan start',wins:'Birincilik',top3:'\u0130lk \u00fc\u00e7',rate:'Kazanma oran\u0131',history:'SON YARI\u015e FORMU',empty:'Bu at i\u00e7in ge\u00e7mi\u015f form kayd\u0131 bulunamad\u0131.',finish:'Bitiri\u015f',hp:'Handikap',weight:'Kilo',pedigree:'PED\u0130GR\u0130'};
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null}
function clean(v:string|null|undefined){let text=(v??'').replace(/\\u([0-9a-f]{4})/gi,(_,code)=>String.fromCharCode(parseInt(code,16)));for(let i=0;i<4;i+=1){if(!/[\u00c3\u00c2\u00e2]/.test(text))break;try{text=decodeURIComponent(escape(text))}catch{break}}return text}
function city(v:string){const x=clean(v);return x==='Istanbul'?'\u0130stanbul':x==='Izmir'?'\u0130zmir':x}
async function getProfile(id:string):Promise<Profile|null>{try{const r=await fetch(`${api}/horse-profiles/${id}`,{cache:'no-store'});return r.ok?await r.json() as Profile:null}catch{return null}}
export const dynamic='force-dynamic';
export default async function HorseProfile({params}:{params:Promise<{id:string}>}){const {id}=await params;const profile=await getProfile(id);if(!profile)return <main className="horse-shell"><a href="/">{t.back}</a><div className="horse-empty">At profili bulunamad\u0131.</div></main>;const {horse,summary,history}=profile;return <main className="horse-shell"><header className="horse-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="horse-title"><p className="eyebrow">{t.tag}</p><h1>{clean(horse.name)}</h1><p>{[horse.country,horse.gender,horse.birth_year].filter(Boolean).join(' \u00b7 ')||'--'}</p></section><section className="horse-kpis"><article><span>{t.starts}</span><strong>{summary.settled_starts}</strong></article><article><span>{t.wins}</span><strong>{summary.wins}</strong></article><article><span>{t.top3}</span><strong>{summary.top3_finishes}</strong></article><article><span>{t.rate}</span><strong>{summary.win_rate==null?'--':`%${summary.win_rate.toFixed(1)}`}</strong></article></section><section className="horse-grid"><article className="horse-card"><p className="eyebrow">{t.history}</p>{history.length?<div className="horse-history">{history.map(item=><a key={`${item.race_id}-${item.program_number}`} href={`/races/${item.race_id}`}><span>{item.race_date}</span><b>{city(item.city)} {item.race_number}. Ko\u015fu</b><small>{item.distance_meters}m \u00b7 {clean(item.surface)}</small><em>{item.finish_position?`${item.finish_position}.`:'--'}</em></a>)}</div>:<p>{t.empty}</p>}</article><aside className="horse-card pedigree"><p className="eyebrow">{t.pedigree}</p><dl><div><dt>Baba</dt><dd>{clean(horse.father)||'--'}</dd></div><div><dt>Anne</dt><dd>{clean(horse.mother)||'--'}</dd></div><div><dt>\u0130lk 3 oran\u0131</dt><dd>{summary.top3_rate==null?'--':`%${summary.top3_rate.toFixed(1)}`}</dd></div></dl></aside></section></main>}