type Entry={program_number:number;horse_name:string|null;win_probability:number|string|null;agf_percent:number|string|null};
type Item={race_id:number;city:string;race_number:number;scheduled_time:string|null;chaos_index:number|string|null;confidence:string|null;primary:Entry;reasons:string[]};
type Shortlist={race_date:string|null;max_chaos:number;items:Item[];disclaimer:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'\u2190 Programa d\u00f6n',tag:'G\u00dcNL\u00dcK KISA L\u0130STE',title:'G\u00fc\u00e7l\u00fc sinyal, kontroll\u00fc okuma.',lead:'Ko\u015fular; model olas\u0131l\u0131\u011f\u0131 ve yar\u0131\u015f belirsizli\u011fi birlikte de\u011ferlendirilerek s\u0131ralan\u0131r.',empty:'Bu e\u015fiklerde incelenecek aday bulunamad\u0131.',probability:'model olas\u0131l\u0131\u011f\u0131',chaos:'belirsizlik',open:'Kart\u0131 incele \u2192',note:'Bu ekran karar deste\u011fidir; kesin sonu\u00e7 veya getiri vaadi i\u00e7ermez.'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function num(v:unknown){const n=typeof v==='number'?v:Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0}
function clean(value:string|null){let s=value??'';for(let i=0;i<3;i+=1){if(!/[\u00c3\u00c2\u00e2]/.test(s))break;try{s=decodeURIComponent(escape(s))}catch{break}}return s}
function city(value:string){const names:Record<string,string>={Istanbul:'\u0130stanbul',Izmir:'\u0130zmir',Elazig:'Elaz\u0131\u011f',Diyarbakir:'Diyarbak\u0131r'};return names[value]??value}
export const dynamic='force-dynamic';
export default async function ShortlistPage(){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());const data=await getJson<Shortlist>(`/recommendations/shortlist?race_date=${today}&max_chaos=65&limit=12`,{race_date:null,max_chaos:65,items:[],disclaimer:t.note});return <main className="decision-shell"><header className="decision-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="decision-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="decision-summary"><article><span>{data.race_date??'--'}</span><strong>{data.items.length}</strong><small>aday</small></article><article><span>Chaos e\u015fi\u011fi</span><strong>{data.max_chaos}</strong><small>{t.chaos}</small></article></section>{data.items.length?<section className="decision-list">{data.items.map(item=><article className="decision-card" key={item.race_id}><div className="decision-card-head"><div><p>{city(item.city)} \u00b7 {item.race_number}. ko\u015fu</p><span>{item.scheduled_time?.slice(0,5)??'--:--'} \u00b7 Chaos {num(item.chaos_index).toFixed(1)}</span></div><b>{item.confidence??'--'}</b></div><div className="decision-primary"><small>{t.probability}</small><h2>{item.primary.program_number}. {clean(item.primary.horse_name)}</h2><strong>%{num(item.primary.win_probability).toFixed(1)}</strong></div><ul>{item.reasons.slice(0,3).map((reason,index)=><li key={`${reason}-${index}`}>{clean(reason)}</li>)}</ul><a href={`/races/${item.race_id}`}>{t.open}</a></article>)}</section>:<div className="decision-empty">{t.empty}</div>}<p className="research-note">{data.disclaimer||t.note}</p></main>}