type Entry={program_number:number;horse_name:string|null;win_probability:number|string|null;agf_percent:number|string|null};
type Item={race_id:number;city:string;race_number:number;scheduled_time:string|null;chaos_index:number|string|null;confidence:string|null;primary:Entry;reasons:string[]};
type Shortlist={race_date:string|null;max_chaos:number;items:Item[];disclaimer:string};
const api=process.env.PEGASUS_API_URL ?? 'http://127.0.0.1:8042/api/v1';
const t={back:'← Programa dön',tag:'GÜNLÜK KISA LİSTE',title:'Güçlü sinyal, kontrollü okuma.',lead:'Koşular; model olasılığı ve yarış belirsizliği birlikte değerlendirilerek sıralanır.',empty:'Bu eşiklerde incelenecek aday bulunamadı.',probability:'model olasılığı',chaos:'belirsizlik',open:'Kartı incele →',note:'Bu ekran karar desteğidir; kesin sonuç veya getiri vaadi içermez.'};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const r=await fetch(`${api}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:fallback}catch{return fallback}}
function num(v:unknown){const n=typeof v==='number'?v:Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0}
function clean(value:string|null){let s=value??'';for(let i=0;i<3;i+=1){if(!/[ÃÂâ]/.test(s))break;try{s=decodeURIComponent(escape(s))}catch{break}}return s}
function city(value:string){const names:Record<string,string>={Istanbul:'İstanbul',Izmir:'İzmir',Elazig:'Elazığ',Diyarbakir:'Diyarbakır'};return names[value]??value}
export const dynamic='force-dynamic';
export default async function ShortlistPage(){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());const data=await getJson<Shortlist>(`/recommendations/shortlist?race_date=${today}&max_chaos=65&limit=12`,{race_date:null,max_chaos:65,items:[],disclaimer:t.note});return <main className="decision-shell"><header className="decision-nav"><a className="brand" href="/"><span>PEGASUS</span><small>RACE INTELLIGENCE</small></a><a href="/">{t.back}</a></header><section className="decision-intro"><p className="eyebrow">{t.tag}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="decision-summary"><article><span>{data.race_date??'--'}</span><strong>{data.items.length}</strong><small>aday</small></article><article><span>Chaos eşiği</span><strong>{data.max_chaos}</strong><small>{t.chaos}</small></article></section>{data.items.length?<section className="decision-list">{data.items.map(item=><article className="decision-card" key={item.race_id}><div className="decision-card-head"><div><p>{city(item.city)} · {item.race_number}. koşu</p><span>{item.scheduled_time?.slice(0,5)??'--:--'} · Chaos {num(item.chaos_index).toFixed(1)}</span></div><b>{item.confidence??'--'}</b></div><div className="decision-primary"><small>{t.probability}</small><h2>{item.primary.program_number}. {clean(item.primary.horse_name)}</h2><strong>%{num(item.primary.win_probability).toFixed(1)}</strong></div><ul>{item.reasons.slice(0,3).map((reason,index)=><li key={`${reason}-${index}`}>{clean(reason)}</li>)}</ul><a href={`/races/${item.race_id}`}>{t.open}</a></article>)}</section>:<div className="decision-empty">{t.empty}</div>}<p className="research-note">{data.disclaimer||t.note}</p></main>}